### ISSUE TITLE
Error querying the character sheet for "name of pilot"

### ISSUE THREAD

**Issue by Kaddeyz** [evemondevteam/evemon#108]
EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()

**Comment by temnyuk** [comment]
Some problem

**Comment by VoodooDog** [comment]
same

EVEMon.Common.Net.HttpWebClientServiceException: A request to esi.evetech.net failed with status: 404 (Not Found). ---> System.Net.Http.HttpRequestException: Der Antwortstatuscode gibt keinen Erfolg an: 404 (Not Found).
   bei System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bei EVEMon.Common.Net.HttpClientServiceRequest.EnsureSuccessStatusCode(HttpResponseMessage response)
   bei EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei EVEMon.Common.Net.HttpWebClientService.<DownloadStreamAsync>d__11`1.MoveNext()
