### ISSUE TITLE
EveMon Crashing When Trying To Add Strategic Cruisers to a Skill Plan

### ISSUE THREAD

**Issue by IcyMidnight** [evemondevteam/evemon#45]
EVEMon Version: 3.0.3.4658
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.14393.0

System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.SkillPlanner.SkillBrowserControl.UpdateContent() in EVEMon\SkillPlanner\SkillBrowserControl.cs:line 252
   at EVEMon.SkillPlanner.SkillBrowserControl.skillSelectControl_SelectedSkillChanged(Object sender, EventArgs e) in EVEMon\SkillPlanner\SkillBrowserControl.cs:line 416
   at EVEMon.Common.Extensions.EventHandlerExtensions.ThreadSafeInvoke[T](EventHandler`1 eventHandler, Object sender, T e) in EVEMon.Common\Extensions\EventHandlerExtensions.cs:line 84
   at EVEMon.SkillPlanner.SkillSelectControl.lbSearchList_SelectedIndexChanged(Object sender, EventArgs e) in EVEMon\SkillPlanner\SkillSelectControl.cs:line 1006
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
  eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
  eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
  eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)

**Comment by Ashilta** [comment]
Hello,

Strange but important question - was the character in question in a Citadel when you tried to add the skill to the plan?

**Comment by aydjay** [comment]
I added amarr strategic cruisers to a new skill plan and the application didn't crash. There may be other repro steps
