### ISSUE TITLE
Crash on startup when Market Order in a Citadel finished.

### ISSUE THREAD

**Issue by RichardSlater** [evemondevteam/evemon#48]
Crash Dump:

```
EVEMon Version: 3.0.3.4658
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.14393.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.Controls.NotificationList.MarketOrdersEndedMessage(MarketOrdersNotificationEventArgs ordersNotification) in EVEMon\Controls\NotificationList.cs:line 624
   at EVEMon.Controls.NotificationList.DisplayTooltip(NotificationEventArgs notification) in EVEMon\Controls\NotificationList.cs:line 522
   at EVEMon.Controls.NotificationList.listBox_MouseMove(Object sender, MouseEventArgs e) in EVEMon\Controls\NotificationList.cs:line 294
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
  eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
  eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
  eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 01s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 01s > Settings.TryDeserializeFromFile - done
0d 0h 00m 01s > Settings.Import - begin
0d 0h 00m 01s > EveMonClient.OnSchedulerChanged
0d 0h 00m 01s > Settings.Import - done
0d 0h 00m 01s > EveMonClient.OnSettingsChanged
0d 0h 00m 01s > Main loop - start
0d 0h 00m 02s > MainWindow.OnLoad
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 02s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 02s > Main window - loaded
0d 0h 00m 02s > EveIDToName.Import - begin
0d 0h 00m 02s > EveIDToName.Import - done
0d 0h 00m 02s > Datafiles.Load - begin
0d 0h 00m 03s > TimeCheck.BeginCheckAsync
0d 0h 00m 03s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 03s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 03s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 05s > Datafiles.Load - done
0d 0h 00m 05s > Settings.ImportData - begin
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - Scetrov
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - Scetrov
0d 0h 00m 06s > EveNotificationType.Import - begin
0d 0h 00m 06s > EveNotificationType.EnsureImportation - done
0d 0h 00m 06s > EveNotificationTextParser.GetExternalParserAsync
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Scetrov
0d 0h 00m 06s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 06s > EveMonClient.OnAPIKeyCollectionChanged
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Scetrov
0d 0h 00m 06s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 08s > List`1.ForEach - The name 'EVEMonConstants' does not exist in the current context
0d 0h 00m 08s > List`1.ForEach - The name 'EVEMonConstants' does not exist in the current context
0d 0h 00m 08s > List`1.ForEach - The name 'EVEMonConstants' does not exist in the current context
0d 0h 00m 08s > List`1.ForEach - The name 'EVEMonConstants' does not exist in the current context
0d 0h 00m 08s > EveNotificationTextParser.OnDownloaded
0d 0h 00m 08s > EveMonClient.OnNotificationSent - Frequency Modulation III completed.
0d 0h 00m 08s > Settings.ImportData - done
0d 0h 00m 08s > EveMonClient.OnSettingsChanged
0d 0h 00m 08s > EveMonClient.OnCharacterQueuedSkillsCompleted - Scetrov
0d 0h 00m 09s > EveMonClient.OnCharacterUpdated - Scetrov
0d 0h 00m 09s > EveMonClient.OnCharacterListUpdated - 5861247 (Scetrov, Raynem, Vortecs)
0d 0h 00m 09s > EveMonClient.OnAPIKeyInfoUpdated - 5861247 (Scetrov, Raynem, Vortecs)
0d 0h 00m 10s > EveMonClient.OnCharacterIndustryJobsCompleted - Scetrov
0d 0h 00m 10s > EveMonClient.OnNotificationSent - 2 industry jobs completed.
0d 0h 00m 11s > EveMonClient.OnCharacterStandingsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterKillLogUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterEVENotificationsUpdated - Scetrov
0d 0h 00m 11s > ConquerableStation.Import - begin
0d 0h 00m 11s > ConquerableStation.GetStationByID - done
0d 0h 00m 11s > EveMonClient.OnCharacterContractsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnContractsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterMarketOrdersUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnNotificationSent - 1 market order expired or fulfilled.
0d 0h 00m 11s > EveMonClient.OnMarketOrdersUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterIndustryJobsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnIndustryJobsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractBidsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterWalletTransactionsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContractItemsDownloaded - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterResearchPointsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLinksUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryPinsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryPinsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryPinsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryPinsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryPinsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLinksUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLinksUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLinksUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLinksUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterContactsUpdated - Scetrov
0d 0h 00m 11s > EveMonClient.OnCharacterWalletJournalUpdated - Scetrov
0d 0h 00m 11s > EveFlag.Import - begin
0d 0h 00m 11s > EveFlag.EnsureImportation - done
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailingListsUpdated - Scetrov
0d 0h 00m 12s > EveMonClient.OnCharacterAssetsUpdated - Scetrov
0d 0h 00m 12s > EveMonClient.OnRefTypesUpdated
0d 0h 00m 12s > UpdateManager.BeginCheckAsync
0d 0h 00m 12s > EveMonClient.OnCharacterSkillQueueUpdated - Scetrov
0d 0h 00m 12s > EveMonClient.OnCharacterImplantSetCollectionChanged - Scetrov
0d 0h 00m 12s > EveMonClient.OnCharacterUpdated - Scetrov
0d 0h 00m 12s > EveMonClient.OnAccountStatusUpdated - 5861247 (Scetrov, Raynem, Vortecs)
0d 0h 00m 13s > EveMonClient.OnCharacterInfoUpdated - Scetrov
0d 0h 00m 13s > EveMonClient.OnCharactersSkillInTrainingUpdated - 5861247 (Scetrov, Raynem, Vortecs)
0d 0h 00m 13s > UpdateManager.OnCheckCompleted
0d 0h 00m 13s > UpdateManager.ScheduleCheck - in 12:00:00
```

Possibly more useful screenshot:

![Screenshot](https://github.com/RichardSlater/github-images/raw/master/evemon-crash-nullreferenceexception-marketordercomplete.png)

**Comment by JimiC** [comment]
@RichardSlater You still playing??? Unbelievable!

**Comment by RichardSlater** [comment]
@JimiC - Hi Mate, technically I'm back.  Now my Daughter has started school I have a bit more time on my hands, and I'm travelling quite a bit for business and inevitably there are few hours at the end of the day when I have free WiFi and time on my hands to play.  Also... quite frankly... I miss EVE and the community.  How are you doing?

**Comment by JimiC** [comment]
So the daughter started school, oh boy, it seems like yesterday when you told me you became a father...
How years flow like water... (it's a local saying).
Hope Ms Slater is doing fine.

Basically I quit EVE last June, but still around to help the new Lead Dev with the transition. I'm now a professional .NET/C# developer (partailly thanks to EVEMon and you) and currently working at [NTUA](https://www.ntua.gr/en/), at the [SmartRUE](http://www.smartrue.gr/) lab. It's very interesting and leaves me little time, which I spend in other projects (see [vscode-icons](https://github.com/robertohuertasm/vscode-icons/)). Honestly, I don't miss EVE (not yet) and mostly I don't miss CCP.

**Comment by RichardSlater** [comment]
Hurrah, so pleased that you became a pro-developer, and, thank you for your kind words. - looking at EVEMon now there is a massive number of new features you have added.  Be proud of your achievement, sounds like your time with EVE and CCP has run its course and now @Ashilta can take on the mantle.

**Comment by Ashilta** [comment]
No pressure huh?!

Regarding your crash report - it's 99% likely to be caused by something to do with citadels. I've kicked back and relaxed over Christmas but I'm getting back on this in the new year. The biggest single obstacle that we have to navigate is that the XML API doesn't really know so much about Citadels, the net result being that we need to move to use the ESI API, which in turn requires an entirely different authentication model - a huge change for EVEMon! I'm hoping to do some defaulting of properties if we detect that a Citadel is involved as a short term solution but it's less than ideal.

**Comment by RichardSlater** [comment]
Yeah, I was looking into the ESI authentication model - looks interesting right up my street actually as most of my paid work is around SSO and APIs.  Was thinking of taking a crack of spiking out adding EVE SSO authentication and building a basic API Tester akin to the existing XML API tester in the EVEMon tools menu - have you done any work or thinking already around how this might work with EVEMon?

**Comment by Ashilta** [comment]
I have, and it's not a pretty change to manage. You a Discord user?

**Comment by RichardSlater** [comment]
Nope - https://discordapp.com/ - I presume?  I'll download now.

**Comment by Ashilta** [comment]
You have mail at your GH profile address

**Comment by RichardSlater** [comment]
I think I was too slow, can you send again?

**Comment by Ashilta** [comment]
Done - about 25 mins on this one

**Comment by XaeonBE** [comment]
I keep getting crashes as well for this same issue :)
