### ISSUE TITLE
Skill Browser Crash

### ISSUE THREAD

**Issue by lmaslanka** [evemondevteam/evemon#53]
When I open the skill browser and select Capital Capacitor Emission Systems (10) the application crashes for me.

EVEMon Version: 3.0.3.4658
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.14986.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.SkillPlanner.SkillSelectControl.tvItems_ItemDrag(Object sender, ItemDragEventArgs e) in EVEMon\SkillPlanner\SkillSelectControl.cs:line 1255
   at System.Windows.Forms.TreeView.OnItemDrag(ItemDragEventArgs e)
   at System.Windows.Forms.TreeView.TvnBeginDrag(MouseButtons buttons, NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
  eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
  eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
  eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 00s > MainWindow.OnLoad
0d 0h 00m 00s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 00s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 00s > Main window - loaded
0d 0h 00m 00s > EveIDToName.Import - begin
0d 0h 00m 00s > EveIDToName.Import - done
0d 0h 00m 00s > Datafiles.Load - begin
0d 0h 00m 01s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 03s > Datafiles.Load - done
0d 0h 00m 03s > Settings.ImportData - begin
0d 0h 00m 04s > EveMonClient.OnCharacterImplantSetCollectionChanged - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterSkillQueueUpdated - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterImplantSetCollectionChanged - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterSkillQueueUpdated - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterImplantSetCollectionChanged - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterSkillQueueUpdated - XXXXX
0d 0h 00m 04s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterImplantSetCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterSkillQueueUpdated - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterImplantSetCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterSkillQueueUpdated - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 05s > EveMonClient.OnAPIKeyCollectionChanged
0d 0h 00m 05s > EveMonClient.OnCharacterPlanCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterPlanCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterPlanCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterPlanCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnCharacterPlanCollectionChanged - XXXXX
0d 0h 00m 05s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 05s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 06s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 06s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 07s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 07s > Settings.ImportData - done
0d 0h 00m 07s > EveMonClient.OnSettingsChanged
0d 0h 00m 08s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterListUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnAPIKeyInfoUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterListUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnAPIKeyInfoUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterListUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnAPIKeyInfoUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnCharacterListUpdated - XXXXX
0d 0h 00m 08s > EveMonClient.OnAPIKeyInfoUpdated - XXXXX
0d 0h 00m 09s > EveMonClient.OnCharacterIndustryJobsCompleted - XXXXX
0d 0h 00m 09s > EveMonClient.OnNotificationSent - 2 industry jobs completed.
0d 0h 00m 09s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - XXXXX
0d 0h 00m 09s > EveMonClient.OnCharacterIndustryJobsUpdated - XXXXX
0d 0h 00m 09s > EveMonClient.OnIndustryJobsUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryPinsUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryPinsUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryLinksUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryLinksUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnCharacterPlanetaryRoutesUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnAccountStatusUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnAccountStatusUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnAccountStatusUpdated - XXXXX
0d 0h 00m 10s > EveMonClient.OnAccountStatusUpdated - XXXXX
0d 0h 00m 10s > UpdateManager.BeginCheckAsync
0d 0h 00m 11s > UpdateManager.OnCheckCompleted
0d 0h 00m 11s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 22s > TimeCheck.CheckFailure - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 216.229.0.179:13
0d 0h 00m 22s > TimeCheck.ScheduleCheck - in 00:01:00
0d 0h 01m 22s > TimeCheck.BeginCheckAsync
0d 0h 01m 43s > TimeCheck.CheckFailure - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 129.6.15.27:13
0d 0h 01m 43s > TimeCheck.ScheduleCheck - in 00:01:00

**Comment by lmaslanka** [comment]
Did some debugging and looks like the issue was due to m_plan being null. The call to m_plan.GetPlannedLevel(skill) == 5 failed because m_plan was null. I have fixed the issue and will create a pull request.

**Comment by kaedys** [comment]
+1, running into this issue constantly on one of my alts as I'm trying to edit a training plan.

**Comment by lmaslanka** [comment]
I fixed the issue and submitted a pull request that was already accepted. The fix should come in the next release.

**Comment by kaedys** [comment]
I see the PR as still being open, no?
