### ISSUE TITLE
Crash Loop on Startup After Deleting Notifications

### ISSUE THREAD

**Issue by Makeshift** [evemondevteam/evemon#60]
I noticed that one of my characters had a bunch of notifications (Expired market orders, contracts, finished planets etc.), so I quickly tried to press X on each of them. After clicking on one, Evemon crashed and now will not start. Every time I try to start Evemon I get:

```EVEMon Version: 3.0.3.4658
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.15063.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe"

System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EVEMon.Common.Scheduling.SimpleScheduleEntry..ctor(SerializableScheduleEntry serial) in EVEMon.Common\Scheduling\SimpleScheduleEntry.cs:line 23
   at EVEMon.Common.Scheduling.Scheduler.Import(SchedulerSettings serial) in EVEMon.Common\Scheduling\Scheduler.cs:line 100
   at EVEMon.Common.Settings.Import() in EVEMon.Common\Settings.cs:line 206
   at EVEMon.Common.Settings.Initialize() in EVEMon.Common\Settings.cs:line 418
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at EVEMon.Program.Main() in EVEMon\Program.cs:line 35
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EVEMon.Common.Scheduling.SimpleScheduleEntry..ctor(SerializableScheduleEntry serial) in EVEMon.Common\Scheduling\SimpleScheduleEntry.cs:line 23
   at EVEMon.Common.Scheduling.Scheduler.Import(SchedulerSettings serial) in EVEMon.Common\Scheduling\Scheduler.cs:line 100
   at EVEMon.Common.Settings.Import() in EVEMon.Common\Settings.cs:line 206
   at EVEMon.Common.Settings.Initialize() in EVEMon.Common\Settings.cs:line 418
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 81<---


System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EVEMon.Common.Scheduling.SimpleScheduleEntry..ctor(SerializableScheduleEntry serial) in EVEMon.Common\Scheduling\SimpleScheduleEntry.cs:line 23
   at EVEMon.Common.Scheduling.Scheduler.Import(SchedulerSettings serial) in EVEMon.Common\Scheduling\Scheduler.cs:line 100
   at EVEMon.Common.Settings.Import() in EVEMon.Common\Settings.cs:line 206
   at EVEMon.Common.Settings.Initialize() in EVEMon.Common\Settings.cs:line 418
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 81


Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
  eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
  eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
  eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 04s > Settings.TryDeserializeFromFile - done
0d 0h 00m 04s > Settings.Import - begin
0d 0h 00m 04s > Settings.Import - done
0d 0h 00m 04s > EveMonClient.OnSettingsChanged
```

Any ideas?

**Comment by Makeshift** [comment]
Fixed the issue by editing my `settings.xml` and removing everything within `<scheduler>`. Not sure how I caused this by attempting to close notifications but there we go.
