### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wvdvegt** [evemondevteam/evemon#70]
Possible fix for:
**System.NullReferenceException: Object reference not set to an instance of an object.
EVEMon.Common.Models.ConquerableStation.<>c__DisplayClass19_0.<GetStationByName>b__0(ConquerableStation station) in EVEMon.Common\Models\ConquerableStation.cs:line 243**
    
Changed line 243 in ConquerableStation.cs from
`: s_conqStationsByID.Values.FirstOrDefault(station => station.Name == name);`
into
` : s_conqStationsByID.Values.FirstOrDefault(station => name.Equals(station.Name));`

**Comment by xartin** [comment]
getting this error also that causes a crash after evemon has been running for several minutes whenever i mouseover the character sheet notification X "radio button"  used to dismiss notifications about contracts needing attention, industry jobs completed or mails received.
  
always reproducible.

EVEMon Version: 3.0.3.4658
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.16299.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.Controls.NotificationList.ContractsEndedMessage(ContractsNotificationEventArgs contractsNotification) in EVEMon\Controls\NotificationList.cs:line 688
   at EVEMon.Controls.NotificationList.DisplayTooltip(NotificationEventArgs notification) in EVEMon\Controls\NotificationList.cs:line 530
   at EVEMon.Controls.NotificationList.listBox_MouseMove(Object sender, MouseEventArgs e) in EVEMon\Controls\NotificationList.cs:line 294
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Datafile report:
  eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (531KiB - c9f5f87b8d330a9807d8a29211547791)
  eve-items-en-US.xml.gzip (1980KiB - 4d7be11780cc5865d858cbbf5d3ed2c5)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (57KiB - 1e561036689c116fd39755ed30c20bda)
  eve-reprocessing-en-US.xml.gzip (102KiB - 7ef72dae81f0dd200ef8f31c90fcb762)
  eve-skills-en-US.xml.gzip (23KiB - 5c6f3a9ea32a6f135b12f82ac6d8d2ce)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 00s > Settings.TryDeserializeFromFile - done
0d 0h 00m 00s > Settings.Import - begin
0d 0h 00m 00s > EveMonClient.OnSchedulerChanged
0d 0h 00m 00s > Settings.Import - done
0d 0h 00m 00s > EveMonClient.OnSettingsChanged
0d 0h 00m 00s > Main loop - start
0d 0h 00m 00s > MainWindow.OnLoad
0d 0h 00m 00s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 00s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 00s > Main window - loaded
0d 0h 00m 00s > EveIDToName.Import - begin
0d 0h 00m 00s > EveIDToName.Import - done
0d 0h 00m 00s > Datafiles.Load - begin
0d 0h 00m 01s > TimeCheck.BeginCheckAsync
0d 0h 00m 01s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 01s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 02s > Datafiles.Load - done
0d 0h 00m 02s > Settings.ImportData - begin
