### ISSUE TITLE
Error on startup after updating to 3.0.1

### ISSUE THREAD

**Issue by malexejev** [evemondevteam/evemon#9]
Happens right on startup, before I can see my characters list. Log below should provide all technical details, but I'm ready to answer any questions.

Technical details of this error:
```
EVEMon Version: 3.0.1.4636
.NET Runtime Version: 4.0.30319.34209
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

System.AggregateException: One or more errors occurred. ---> System.MethodAccessException: Attempt by method 'EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync()' to access method 'System.Threading.Tasks.Task.get_CompletedTask()' failed.
   at EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync() in EVEMon.Common\Service\EveIDToName.cs:line 231
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__9.MoveNext() in EVEMon.Common\Service\EveIDToName.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 90
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at EVEMon.Program.Main() in EVEMon\Program.cs:line 34
---> (Inner Exception #0) System.MethodAccessException: Attempt by method 'EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync()' to access method 'System.Threading.Tasks.Task.get_CompletedTask()' failed.
   at EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync() in EVEMon.Common\Service\EveIDToName.cs:line 231
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__9.MoveNext() in EVEMon.Common\Service\EveIDToName.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 90<---


System.MethodAccessException: Attempt by method 'EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync()' to access method 'System.Threading.Tasks.Task.get_CompletedTask()' failed.
   at EVEMon.Common.Service.EveIDToName.UpdateOnOneSecondTickAsync() in EVEMon.Common\Service\EveIDToName.cs:line 231
   at EVEMon.Common.Service.EveIDToName.<EveMonClient_TimerTick>d__9.MoveNext() in EVEMon.Common\Service\EveIDToName.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EVEMon.Program.<StartupAsync>d__4.MoveNext() in EVEMon\Program.cs:line 90


Datafile report:
  eve-blueprints-en-US.xml.gzip (193KiB - 8d9de77fb1705dd1e739ba10c583eb03)
  eve-certificates-en-US.xml.gzip (44KiB - e30974b3980b6bd80f21b71ffa1d0ebd)
  eve-geography-en-US.xml.gzip (531KiB - c60dd6b987340ff7d848f7eedc5a39c4)
  eve-items-en-US.xml.gzip (1761KiB - b534807e3fbd97ff8955a024fd8bc93b)
  eve-masteries-en-US.xml.gzip (20KiB - 7b07e6d5609b7277c3cbf4e486430240)
  eve-properties-en-US.xml.gzip (53KiB - 6c5771edd993e540d77679daf91e2c35)
  eve-reprocessing-en-US.xml.gzip (97KiB - 0274d4572164cf2ecdebc36b887886fd)
  eve-skills-en-US.xml.gzip (23KiB - 72e19887522d7cf27e077406618e3872)


Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.Main - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 05s > Settings.TryDeserializeFromFile - done
0d 0h 00m 05s > Settings.Import - begin
0d 0h 00m 05s > EveMonClient.OnSchedulerChanged
0d 0h 00m 05s > Settings.Import - done
0d 0h 00m 05s > Settings.Import
0d 0h 00m 05s > Main loop - start
0d 0h 00m 05s > MainWindow.OnLoad
0d 0h 00m 05s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 05s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 05s > Main window - loaded
0d 0h 00m 05s > Datafiles.Load - begin
0d 0h 00m 06s > <>c.<ScheduleCheck>b__3_0
0d 0h 00m 06s > Program.Main
0d 0h 00m 06s > Closed
```

**Comment by JimiC** [comment]
Install .NET Framework 4.6.1. (4.0.30319.42000). You have.NET 4.5.2 (4.0.30319.34209).
